[theme]
base="light"

backgroundColor="#FFFFFF"     
secondaryBackgroundColor="#f0f0f0ff"   
textColor="#000000"             
primaryColor="#ff0000ff"         
sidebar = {backgroundColor="#1f2c5c",secondaryBackgroundColor="#f0f0f0ff",textColor="#FFFFFF"}